name: CI - Tests

on: push

jobs:
  test:
    name: Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x']
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn install

      - name: Build App
        run: yarn build

      - name: Run tests with jest
        run: yarn test:ci
